before_script:
  - cp config/database.yml.example config/database.yml
  - cp .env.example .env
  - cp .coveralls.yml.example .converalls.yml
  - psql -c 'create database "answers_test";' -U postgres
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare --trace
bundler_args: --without development
language: ruby
rvm:
  - ruby-1.9.3
  - ruby-2.1.2
services:
  - elasticsearch
