before_script:
  - cp .coveralls.yml.example .converalls.yml
  - psql -c 'create database "answers_test";' -U postgres
  - rake answers:testing:dummy_app 
bundler_args: --without development
language: ruby
rvm:
  - ruby-1.9.3
  - ruby-2.1.2
services:
  - elasticsearch
env:
  - DB=postgresql
  - DB=mysql