source 'https://api.berkshelf.com'

cookbook 'apt'
cookbook 'bash-completion'
cookbook 'cacert'
cookbook 'chef-solo-search'
cookbook 'cron'
cookbook 'elasticsearch'
cookbook 'fail2ban'
cookbook 'git'
cookbook 'hostname'
cookbook 'imagemagick'
cookbook 'libqt4'
cookbook 'logwatch'
cookbook 'kibana', git: 'https://github.com/lusis/chef-kibana.git'
cookbook 'logstash'
cookbook 'memcached'
cookbook 'nano'
cookbook 'ntp'
cookbook 'openssl'
cookbook 'passenger'
cookbook 'postgresql', git: 'https://github.com/phlipper/chef-postgresql.git'
cookbook 'rbenv'
cookbook 'ruby_build'
cookbook 'ssl_certificate'
cookbook 'sudo'
cookbook 'swap'
cookbook 'ubuntu'
cookbook 'users_solo'
cookbook 'wordnet', path: 'kitchen/site-cookbooks/wordnet'
