# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c7a0993ffeb43fc4e93e762b39bb0da22036a60a15932ace5f3f78d60b619487727a5943ede1bd2c2b1a1cab29faa812a7cdbfee82714beb8e12202d2c39a09

test:
  secret_key_base: 1b90d00f84589cad36f3239836d3899fa6a533a44cda3671295330e04f35627b084d70df988cf35321ced96eae69b48610aa0872f4b8d63dc5b0cfe4f1f05361

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
